use drinkingBuddies;

INSERT IGNORE INTO BeerTypes (`Style`, `BeerTypeId`) VALUES 
('English Oatmeal Stout', '1'),
('Russian Imperial Stout', '2'),
('Scottish Ale', '3'),
('American Imperial Stout', '4'),
('American Cream Ale', '5'),
('Japanese Rice Lager', '6'),
('American Lager', '7'),
('American IPA', '8'),
('German Bock', '9'),
('English Stout', '10'),
('English Bitter', '11'),
('Belgian Witbier', '12'),
('American Strong Ale', '13'),
('American Pale Wheat Ale', '14'),
('Berliner Weisse', '15'),
('American Pale Ale (APA)', '16'),
('British Barleywine', '17'),
('American Black Ale', '18'),
('Baltic Porter', '19'),
('American Adjunct Lager', '20'),
('European Pale Lager', '21'),
('American Porter', '22'),
('Fruit and Field Beer', '23'),
('American Imperial IPA', '24'),
('American Wild Ale', '25'),
('Irish Red Ale', '26'),
('English Pale Ale', '27'),
('American Amber / Red Lager', '28'),
('Belgian Saison', '29'),
('Belgian IPA', '30'),
('Rye Beer', '31'),
('Belgian Quadrupel (Quad)', '32'),
('German Hefeweizen', '33'),
('American Stout', '34'),
('Smoke Beer', '35'),
('Belgian Tripel', '36'),
('American Amber / Red Ale', '37'),
('Pumpkin Beer', '38'),
('German Maibock', '39'),
('German Dunkelweizen', '40'),
('Belgian Dark Ale', '41'),
('Vienna Lager', '42'),
('English Extra Special / Strong Bitter (ESB)', '43'),
('English Sweet / Milk Stout', '44'),
('Scotch Ale / Wee Heavy', '45'),
('Leipzig Gose', '46'),
('German Pilsner', '47'),
('German Kristalweizen', '48'),
('German Märzen / Oktoberfest', '49'),
('American Brown Ale', '50'),
('American Blonde Ale', '51'),
('Bohemian Pilsener', '52'),
('American Barleywine', '53'),
('Foreign / Export Stout', '54'),
('Belgian Strong Pale Ale', '55'),
('European Export / Dortmunder', '56'),
('French Bière de Garde', '57'),
('California Common / Steam Beer', '58'),
('English India Pale Ale (IPA)', '59'),
('Winter Warmer', '60'),
('German Helles', '61'),
('American Imperial Red Ale', '62'),
('European Strong Lager', '63'),
('Belgian Dubbel', '64'),
('English Porter', '65'),
('Belgian Gueuze', '66'),
('German Rauchbier', '67'),
('German Altbier', '68'),
('English Brown Ale', '69'),
('American Light Lager', '70'),
('European Dark Lager', '71'),
('Belgian Strong Dark Ale', '72'),
('Belgian Pale Ale', '73'),
('German Doppelbock', '74'),
('German Kölsch', '75'),
('German Schwarzbier', '76'),
('Herb and Spice Beer', '77'),
('English Old Ale', '78'),
('German Kellerbier / Zwickelbier', '79'),
('Munich Dunkel Lager', '80'),
('Chile Beer', '81'),
('English Pale Mild Ale', '82'),
('Irish Dry Stout', '83'),
('German Weizenbock', '84'),
('American Brett', '85'),
('Belgian Fruit Lambic', '86'),
('Wild/Sour Beers', '87'),
('Robust Porter', '88'),
('Smoke Porter', '89'),
('American Wheatwine Ale', '90'),
('American Dark Wheat Ale', '91'),
('Flanders Oud Bruin', '92'),
('German Roggenbier', '93'),
('Finnish Sahti', '94'),
('American Malt Liquor', '95'),
('American Imperial Pilsner', '96'),
('Belgian Blonde Ale', '97'),
('American Imperial Porter', '98'),
('Scottish Gruit / Ancient Herbed Ale', '99'),
('American Brut IPA', '100'),
('Flanders Red Ale', '101'),
('Low Alcohol Beer', '102'),
('English Dark Mild Ale', '103'),
('New England IPA', '104'),
('English Strong Ale', '105'),
('Japanese Happoshu', '106'),
('Russian Kvass', '107'),
('Braggot', '108'),
('Belgian Lambic', '109'),
('Bière de Champagne / Bière Brut', '110'),
('German Eisbock', '111'),
('Belgian Faro', '112');